---
source: crates/ruff_linter/src/rules/flake8_datetimez/mod.rs
---
error[DTZ003]: 4:1: `datetime.datetime.utcnow()` used

 --> DTZ003.py:3:12
  |
3 | # qualified
4 | datetime.datetime.utcnow()
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^
5 | 
6 | from datetime import datetime
  |
  = help: Use `datetime.datetime.now(tz=...)` instead
error[DTZ003]: 9:1: `datetime.datetime.utcnow()` used

  --> DTZ003.py:8:14
   |
 8 | # unqualified
 9 | datetime.utcnow()
   | ^^^^^^^^^^^^^^^^^
10 | 
11 | # uses `astimezone` method
   |
   = help: Use `datetime.datetime.now(tz=...)` instead
