---
source: crates/ruff_linter/src/rules/flake8_bugbear/mod.rs
---
error[B025]: 19:8: try-except block with duplicate exception `ValueError`

  --> B025.py:19:8
   |
17 | except ValueError:
18 |     a = 2
19 | except ValueError:
   |        ^^^^^^^^^^
20 |     a = 2
   |
error[B025]: 28:8: try-except block with duplicate exception `pickle.PickleError`

  --> B025.py:28:8
   |
26 | except ValueError:
27 |     a = 2
28 | except pickle.PickleError:
   |        ^^^^^^^^^^^^^^^^^^
29 |     a = 2
   |
error[B025]: 35:8: try-except block with duplicate exception `ValueError`

  --> B025.py:35:8
   |
33 | except (ValueError, TypeError):
34 |     a = 2
35 | except ValueError:
   |        ^^^^^^^^^^
36 |     a = 2
37 | except (OSError, TypeError):
   |
error[B025]: 37:18: try-except block with duplicate exception `TypeError`

  --> B025.py:37:18
   |
35 | except ValueError:
36 |     a = 2
37 | except (OSError, TypeError):
   |                  ^^^^^^^^^
38 |     a = 2
   |
