---
source: crates/ruff_linter/src/rules/flake8_bandit/mod.rs
---
error[S112]: 3:1: `try`-`except`-`continue` detected, consider logging the exception

 --> S112.py:2:9
  |
1 |   try:
2 |       pass
3 | / except Exception:
4 | |     continue
  | |____________^
5 |   
6 |   try:
  |
error[S112]: 8:1: `try`-`except`-`continue` detected, consider logging the exception

  --> S112.py:7:9
   |
 6 |   try:
 7 |       pass
 8 | / except:
 9 | |     continue
   | |____________^
10 |   
11 |   try:
   |
error[S112]: 13:1: `try`-`except`-`continue` detected, consider logging the exception

  --> S112.py:12:9
   |
11 |   try:
12 |       pass
13 | / except (Exception,):
14 | |     continue
   | |____________^
15 |   
16 |   try:
   |
error[S112]: 18:1: `try`-`except`-`continue` detected, consider logging the exception

  --> S112.py:17:9
   |
16 |   try:
17 |       pass
18 | / except (Exception, ValueError):
19 | |     continue
   | |____________^
20 |   
21 |   try:
   |
